import re
import os

print("Building WariSeva AI Full Multilingual Engine...")

# Read script.js
with open('static/script.js', 'r', encoding='utf-8') as f:
    js_content = f.read()

# We will prepare comprehensive translations dictionary
multilingual_dict_js = '''    // Comprehensive Multilingual Translation Dictionaries (English, Marathi, Hindi)
    const i18n = {
        en: {
            lang_code: "en-IN",
            tagline: "Your safety, one tap away.",
            value_prop: "\\"We don't just report an emergency — we coordinate the response behind the SOS.\\"",
            value_flow: "QR Wristband → Exact Identification → Protected Medical Profile → AI Emergency Coordination",
            demo_desc: "DEMO DATA • SIMULATED RESPONSE",
            reset_demo: "🔄 RESET DEMO",
            nav_home: "Home",
            nav_emergency: "Emergency",
            nav_volunteer: "Volunteer",
            nav_responder: "Medical Facility",
            nav_map: "Safety Network",
            nav_qr_scanner: "Wristband / QR",
            nav_command: "Command Center",
            wristband_id_btn: "Wristband ID",
            palkhi_safety: "🚩 Palkhi Safety Coordination",
            hero_tagline: "\\"Your safety, one tap away.\\"",
            hero_subtext: "Emergency coordination and safety assistance for the Sant Dnyaneshwar & Sant Tukaram Palkhi Wari.",
            sos_btn_text: "🚨 EMERGENCY / SOS",
            sos_btn_sub: "PRESS FOR HELP • SOS",
            current_zone: "Zone 04 — Saswad Palkhi Maidan",
            act_where_am_i: "Where am I?",
            act_medical_help: "Medical Help",
            act_safety_map: "Safety Map",
            quick_services_title: "🛡️ Quick Safety Services",
            see_all: "See All 13 Facilities →",
            svc_water: "Water",
            svc_water_sub: "Drinking Water Station",
            svc_toilets: "Toilets",
            svc_toilets_sub: "Mobile Sanitation Units",
            svc_rest: "Rest Area",
            svc_rest_sub: "Pilgrim Rest Camp",
            svc_medical: "Medical Center",
            svc_medical_sub: "First Aid & Clinic",
            svc_food: "Food / Prasad",
            svc_food_sub: "Annachhatra & Meals",
            svc_hospitals: "Hospitals",
            svc_hospitals_sub: "Trauma & Emergency Care",
            safety_id_title: "WariSeva Safety ID",
            safety_id_sub: "Register demo profile for quick identification and instant SOS dispatch.",
            label_full_name: "Full Name",
            label_phone: "Mobile Number",
            btn_create_id: "CREATE SAFETY ID",
            id_active_badge: "Safety ID Active & Registered",
            btn_change_profile: "Change / Register Another Profile",
            em_kicker: "HELP IS ON THE WAY • KEEP CALM",
            em_help_requested: "EMERGENCY HELP REQUESTED",
            palkhi_zone: "Wari Palkhi Zone",
            nearest_landmark: "Nearest Landmark",
            gps_precision: "GPS Precision",
            response_timeline: "📊 Emergency Response Timeline",
            btn_open_tactical_map: "🗺️ VIEW TACTICAL MAP",
            btn_report_another: "REPORT ANOTHER EMERGENCY",
            filter_label: "Filters:",
            map_pin_prompt: "Select Any Map Pin",
            map_pin_prompt_sub: "Click any service marker or emergency incident to view distance, route, and details.",
            btn_focus_pin: "🎯 FOCUS ON MAP",
            services_page_title: "Wari Safety Directory",
            services_page_sub: "Find verified essential facilities across all 12 pilgrimage route sectors.",
            select_zone: "Select Sector:",
            modal_sos_title: "Trigger Emergency SOS?",
            modal_sos_msg: "This will capture your exact coordinates and immediately alert the nearest Palkhi route volunteer and medical responder unit.",
            modal_using_id: "Using Safety ID:",
            btn_cancel: "CANCEL",
            btn_confirm_sos: "DISPATCH SOS",
            acquiring_gps: "Acquiring GPS Position...",
            mapping_checkpoint: "Mapping to nearest Palkhi route checkpoint",
            active_em_title: "ACTIVE EMERGENCY IN PROGRESS",
            view_live_response: "VIEW LIVE RESPONSE →",
            
            // Volunteer Dashboard Strings
            vol_login_title: "VOLUNTEER LOGIN",
            vol_login_sub: "Official Wari Emergency Response Portal",
            vol_demo_badge: "DEMO ACCOUNT",
            vol_demo_creds: "Demo ID: V-001 • Password: demo123 (Ramesh Kulkarni • Zone 04 • First Aid Certified)",
            vol_quick_fill: "⚡ AUTO-FILL DEMO CREDENTIALS",
            vol_id_label: "Volunteer ID",
            vol_pass_label: "Password",
            vol_login_btn: "🔐 LOGIN AS VOLUNTEER",
            vol_logout_btn: "🚪 LOGOUT",
            vol_network_kicker: "WARISEVA VERIFIED VOLUNTEER NETWORK",
            vol_sector_info: "Assigned: Zone 04 — Saswad Palkhi Maidan • Skills: First Aid Certified, CPR",
            vol_status_avail: "🟢 STATUS: AVAILABLE",
            vol_open_scanner: "📸 OPEN QR SCANNER",
            vol_inc_dispatch: "🚨 INCOMING EMERGENCY DISPATCH",
            vol_accept_btn: "🦺 ACCEPT CASE",
            vol_enroute_btn: "🚶 START RESPONSE (EN ROUTE)",
            vol_arrived_btn: "🤝 I'M WITH PATIENT",
            vol_scan_wb_btn: "📸 SCAN PATIENT WRISTBAND",
            vol_escalate_btn: "🏥 ESCALATE TO HOSPITAL",
            vol_status_responding: "🟡 RESPONDING",
            vol_status_verified: "✓ VERIFIED",

            // Hospital Dashboard Strings
            hosp_login_title: "MEDICAL FACILITY LOGIN",
            hosp_login_sub: "Hospital & Trauma Center Coordination Portal",
            hosp_demo_badge: "DEMO FACILITY",
            hosp_demo_creds: "Facility ID: H-001 • Password: demo123 (WariSeva Medical Camp — Zone 04 • 1 Bed Available)",
            hosp_quick_fill: "⚡ AUTO-FILL DEMO CREDENTIALS",
            hosp_id_label: "Facility ID",
            hosp_pass_label: "Password",
            hosp_login_btn: "🔐 LOGIN AS MEDICAL FACILITY",
            hosp_logout_btn: "🚪 LOGOUT",
            hosp_network_kicker: "WARISEVA MEDICAL FACILITY NETWORK",
            hosp_bed_avail: "1 AVAILABLE",
            hosp_bed_reserved: "1 RESERVED",
            hosp_accepting_chip: "ACCEPTING EMERGENCIES",
            hosp_inc_intake: "🏥 INCOMING PATIENT INTAKE",
            hosp_accept_btn: "🏥 ACCEPT PATIENT (RESERVE BED)",
            hosp_arrived_btn: "📍 PATIENT ARRIVED",
            hosp_treatment_btn: "🩺 TREATMENT STARTED",
            hosp_transfer_btn: "🚑 MARK TRANSFERRED",
            hosp_resolve_btn: "✅ CASE RESOLVED",
            hosp_resolved_banner: "✅ STATUS: EMERGENCY RESOLVED. Treatment successfully administered.",

            // Command Center Strings
            cmd_title: "🛰️ TACTICAL COMMAND CENTER",
            cmd_sub: "Wari Emergency Operations, Dispatch & Verification Hub",
            cmd_tab_ops: "📊 Operations",
            cmd_tab_vols: "🦺 Volunteers",
            cmd_tab_hosps: "🏥 Medical Network",
            cmd_tab_dive: "🚨 Live Incident Deep Dive",
            cmd_stat_registered: "Total Registered",
            cmd_stat_verified: "Verified",
            cmd_stat_available: "Available",
            cmd_stat_responding: "Responding",
            cmd_stat_pending: "Pending Verification",
            cmd_stat_accepting: "Accepting Emergencies",
            cmd_stat_critical: "Critical",
            cmd_stat_high: "High",
            cmd_stat_resolved: "Resolved",

            // AI Recommendation
            ai_rec_title: "🤖 AI RESPONDER RECOMMENDATION",
            ai_why_heading: "Why this responder?",
            ai_reason_1: "✓ First-aid certified",
            ai_reason_2: "✓ 350m from patient",
            ai_reason_3: "✓ Inside Zone 04",
            ai_reason_4: "✓ Available on route",
            ai_kicker: "AI-assisted responder recommendation",

            // Timeline Steps Translation (Title & Description)
            timeline_steps: {
                1: { title: "🚨 Step 1: SOS Sent & Registered", desc: "Emergency registered in central incident registry." },
                2: { title: "📍 Step 2: Exact Location Acquired", desc: "GPS telemetry coordinates acquired: 18.3444, 74.0305 (±5m precision)." },
                3: { title: "🗺️ Step 3: Wari Zone Identified", desc: "Location matched to Zone 04 — Saswad Palkhi Maidan." },
                4: { title: "🔴 Step 4: Emergency Severity Classified", desc: "Severity: Critical • Type: Medical Emergency / Triage Priority." },
                5: { title: "🤖 Step 5: AI Responder Recommendation", desc: "Matched: Ramesh Kulkarni (V-001) • Score: 94/100 (First Aid Certified + Available + Nearby + Same Wari Zone)." },
                6: { title: "🔔 Step 6: Volunteer Alert Sent", desc: "Emergency dispatch notification sent to nearest volunteer device." },
                7: { title: "🦺 Step 7: Volunteer Accepted", desc: "Volunteer Ramesh Kulkarni confirmed and accepted dispatch." },
                8: { title: "🚶 Step 8: Volunteer En Route", desc: "Moving toward emergency location (320m • ETA 2 min)." },
                9: { title: "📍 Step 9: Volunteer Arrived", desc: "Volunteer arrived at emergency location (0m • With Patient). First aid in progress." },
                10: { title: "🏥 Step 10: Hospital Accepted", desc: "Medical facility accepted case. Emergency Bed Reserved: 1." },
                11: { title: "🚑 Step 11: Patient Expected / Arrived", desc: "Patient arrived at medical facility. Clinical triage and assessment started." },
                12: { title: "✅ Step 12: Case Resolved", desc: "Case Resolved. Patient admitted / emergency assistance completed successfully." }
            },

            // Exact Spoken Audio Narration Sentences
            timeline_narrations: {
                1: "SOS received. Emergency registered.",
                2: "Exact location acquired.",
                3: "Wari zone identified. Saswad Palkhi Maidan.",
                4: "Emergency classified as critical.",
                5: "Nearest suitable volunteer identified.",
                6: "Emergency alert sent to the nearest volunteer.",
                7: "Volunteer has accepted the emergency.",
                8: "Volunteer is on the way.",
                9: "Volunteer has arrived at the emergency location.",
                10: "Suitable medical facility identified.",
                11: "Hospital has accepted the case. Patient transfer initiated.",
                12: "Emergency response completed successfully."
            },

            // Status Tags
            tag_pending: "○ PENDING",
            tag_completed: "✓ COMPLETED",
            tag_waiting_vol: "⏳ WAITING FOR VOLUNTEER",
            tag_waiting_hosp: "⏳ WAITING FOR HOSPITAL",
            tag_processing: "🔵 PROCESSING...",
            tag_locked: "🔒 LOCKED",

            // Emergency notification
            notif_title: "🚨 NEW EMERGENCY",
            notif_msg: "Critical medical emergency reported in Zone 04. Volunteer action required."
        },
        mr: {
            lang_code: "mr-IN",
            tagline: "आपली सुरक्षा, एका स्पर्शात.",
            value_prop: "\\"आम्ही केवळ आपत्कालीन नोंद करत नाही — मदतीची संपूर्ण यंत्रणा समन्वयित करतो.\\"",
            value_flow: "QR रिस्टबँड → अचूक ओळख → सुरक्षित वैद्यकीय माहिती → AI आपत्कालीन समन्वय",
            demo_desc: "डेमो डेटा • सिम्युलेटेड प्रतिसाद",
            reset_demo: "🔄 रिसेट डेमो",
            nav_home: "मुख्य पान",
            nav_emergency: "आपत्कालीन",
            nav_volunteer: "स्वयंसेवक",
            nav_responder: "वैद्यकीय केंद्र",
            nav_map: "सुरक्षा नकाशा",
            nav_qr_scanner: "रिस्टबँड / QR",
            nav_command: "नियंत्रण कक्ष",
            wristband_id_btn: "रिस्टबँड ID",
            palkhi_safety: "🚩 पालखी सुरक्षा समन्वय",
            hero_tagline: "\\"आपली सुरक्षा, एका स्पर्शात.\\"",
            hero_subtext: "संत ज्ञानेश्वर व संत तुकाराम पालखी वारीसाठी डिजिटल आरोग्य व सुरक्षा यंत्रणा.",
            sos_btn_text: "🚨 आपत्कालीन मदत / SOS",
            sos_btn_sub: "मदतीसाठी दाबा • SOS",
            current_zone: "झोन ०४ — सासवड पालखी मैदान",
            act_where_am_i: "मी कुठे आहे?",
            act_medical_help: "वैद्यकीय मदत",
            act_safety_map: "सुरक्षा नकाशा",
            quick_services_title: "🛡️ तातडीच्या वारी सुविधा",
            see_all: "सर्व १३ सुविधा पहा →",
            svc_water: "पिण्याचे पाणी",
            svc_water_sub: "शुद्ध जल केंद्र",
            svc_toilets: "स्वच्छतागृह",
            svc_toilets_sub: "मोबाईल टॉयलेट",
            svc_rest: "विश्रांती",
            svc_rest_sub: "विश्रांती मंडप",
            svc_medical: "आरोग्य केंद्र",
            svc_medical_sub: "प्रथमोपचार तंबू",
            svc_food: "अन्नछत्र / प्रसाद",
            svc_food_sub: "अन्नदान व भोजन",
            svc_hospitals: "रुग्णालये",
            svc_hospitals_sub: "ट्रॉमा व आपत्कालीन कक्ष",
            safety_id_title: "वारीसेवा सुरक्षा ओळखपत्र",
            safety_id_sub: "तातडीच्या मदतीसाठी आपली माहिती नोंदवा.",
            label_full_name: "पूर्ण नाव",
            label_phone: "मोबाईल नंबर",
            btn_create_id: "सुरक्षा आयडी तयार करा",
            id_active_badge: "सुरक्षा ओळखपत्र सक्रिय आहे",
            btn_change_profile: "दुसरे ओळखपत्र नोंदवा",
            em_kicker: "मदत येत आहे • घाबरू नका",
            em_help_requested: "आपत्कालीन मदत मागितली आहे",
            palkhi_zone: "पालखी झोन",
            nearest_landmark: "जवळची खूण",
            gps_precision: "GPS अचूकता",
            response_timeline: "📊 आपत्कालीन प्रतिसाद कालरेषा",
            btn_open_tactical_map: "🗺️ संपूर्ण नकाशा पहा",
            btn_report_another: "दुसरी मदत नोंदवा",
            filter_label: "फिल्टर:",
            map_pin_prompt: "नकाशावरील पिन निवडा",
            map_pin_prompt_sub: "तपशील, अंतर आणि मार्ग पाहण्यासाठी कोणत्याही पिनवर क्लिक करा.",
            btn_focus_pin: "🎯 नकाशावर पहा",
            services_page_title: "वारी सुरक्षा सुविधा डिरेक्टरी",
            services_page_sub: "सर्व १२ पालखी टप्प्यांवरील सत्यापित सुविधा.",
            select_zone: "झोन निवडा:",
            modal_sos_title: "तातडीची मदत मागवायची का?",
            modal_sos_msg: "आपले थेट लोकेशन नोंदवून सर्वात जवळच्या वारी स्वयंसेवकाला तात्काळ पाठवले जाईल.",
            modal_using_id: "वापरत असलेला आयडी:",
            btn_cancel: "रद्द करा",
            btn_confirm_sos: "मदत पाठवा (SOS)",
            acquiring_gps: "GPS लोकेशन मिळवत आहे...",
            mapping_checkpoint: "जवळच्या पालखी चेकपॉईंटशी जोडत आहे",
            active_em_title: "आपत्कालीन मदत सक्रिय आहे",
            view_live_response: "प्रतिसाद पहा →",

            // Volunteer Dashboard Strings
            vol_login_title: "स्वयंसेवक लॉगिन",
            vol_login_sub: "अधिकृत वारी आपत्कालीन प्रतिसाद पोर्टल",
            vol_demo_badge: "डेमो खाते",
            vol_demo_creds: "डेमो ID: V-001 • पासवर्ड: demo123 (रमेश कुलकर्णी • झोन ०४ • प्रथमोपचार प्रमाणित)",
            vol_quick_fill: "⚡ डेमो माहिती भरा",
            vol_id_label: "स्वयंसेवक ID",
            vol_pass_label: "पासवर्ड",
            vol_login_btn: "🔐 स्वयंसेवक लॉगिन करा",
            vol_logout_btn: "🚪 लॉगआउट",
            vol_network_kicker: "वारीसेवा सत्यापित स्वयंसेवक नेटवर्क",
            vol_sector_info: "नेमणूक: झोन ०४ — सासवड पालखी मैदान • कौशल्ये: प्रथमोपचार प्रमाणित, CPR",
            vol_status_avail: "🟢 स्थिती: उपलब्ध",
            vol_open_scanner: "📸 QR स्कॅनर उघडा",
            vol_inc_dispatch: "🚨 नवीन आपत्कालीन मदत सूचना",
            vol_accept_btn: "🦺 केस स्वीकारा",
            vol_enroute_btn: "🚶 मदतीसाठी निघा (मार्गस्थ)",
            vol_arrived_btn: "🤝 मी रुग्णाजवळ पोहोचलो",
            vol_scan_wb_btn: "📸 रुग्णाचा रिस्टबँड स्कॅन करा",
            vol_escalate_btn: "🏥 रुग्णालयाकडे संदर्भ द्या",
            vol_status_responding: "🟡 प्रतिसाद देत आहे",
            vol_status_verified: "✓ सत्यापित",

            // Hospital Dashboard Strings
            hosp_login_title: "वैद्यकीय केंद्र लॉगिन",
            hosp_login_sub: "रुग्णालय व ट्रॉमा केंद्र समन्वय पोर्टल",
            hosp_demo_badge: "डेमो केंद्र",
            hosp_demo_creds: "केंद्र ID: H-001 • पासवर्ड: demo123 (वारीसेवा मेडिकल कॅम्प — झोन ०४ • १ बेड उपलब्ध)",
            hosp_quick_fill: "⚡ डेमो माहिती भरा",
            hosp_id_label: "केंद्र ID",
            hosp_pass_label: "पासवर्ड",
            hosp_login_btn: "🔐 वैद्यकीय केंद्र लॉगिन करा",
            hosp_logout_btn: "🚪 लॉगआउट",
            hosp_network_kicker: "वारीसेवा वैद्यकीय केंद्र नेटवर्क",
            hosp_bed_avail: "१ उपलब्ध",
            hosp_bed_reserved: "१ राखीव",
            hosp_accepting_chip: "रुग्ण स्वीकारत आहे",
            hosp_inc_intake: "🏥 नवीन रुग्ण आगमन",
            hosp_accept_btn: "🏥 रुग्ण स्वीकारा (बेड राखीव)",
            hosp_arrived_btn: "📍 रुग्ण पोहोचला",
            hosp_treatment_btn: "🩺 उपचार सुरू झाले",
            hosp_transfer_btn: "🚑 रुग्ण हस्तांतरित झाला",
            hosp_resolve_btn: "✅ केस पूर्ण झाली",
            hosp_resolved_banner: "✅ स्थिती: आपत्कालीन केस यशस्वीरित्या पूर्ण झाली. उपचार यशस्वीरित्या दिले गेले.",

            // Command Center Strings
            cmd_title: "🛰️ नियंत्रण कक्ष",
            cmd_sub: "वारी आपत्कालीन ऑपरेशन्स, पाठपुरावा व पडताळणी केंद्र",
            cmd_tab_ops: "📊 कार्यप्रणाली",
            cmd_tab_vols: "🦺 स्वयंसेवक",
            cmd_tab_hosps: "🏥 आरोग्य यंत्रणा",
            cmd_tab_dive: "🚨 थेट घटना विश्लेषण",
            cmd_stat_registered: "एकूण नोंदणीकृत",
            cmd_stat_verified: "सत्यापित",
            cmd_stat_available: "उपलब्ध",
            cmd_stat_responding: "प्रतिसाद देत आहेत",
            cmd_stat_pending: "पडताळणी प्रलंबित",
            cmd_stat_accepting: "मदत स्वीकारत आहेत",
            cmd_stat_critical: "गंभीर",
            cmd_stat_high: "उच्च",
            cmd_stat_resolved: "पूर्ण झालेल्या केसेस",

            // AI Recommendation
            ai_rec_title: "🤖 AI-सहाय्यित प्रतिसादकाची शिफारस",
            ai_why_heading: "निवडण्याची कारणे:",
            ai_reason_1: "✓ प्रथमोपचार प्रमाणित",
            ai_reason_2: "✓ ३५० मी अंतर (२ मिनिटे)",
            ai_reason_3: "✓ त्याच वारी क्षेत्रात (झोन ०४)",
            ai_reason_4: "✓ मार्गावर उपलब्ध",
            ai_kicker: "AI-सहाय्यित प्रतिसादकाची शिफारस",

            // Timeline Steps Translation (Exact Marathi as requested)
            timeline_steps: {
                1: { title: "🚨 पायरी १: SOS पाठवले आणि नोंदणी झाली", desc: "आपत्कालीन घटना केंद्रीय नोंदणी प्रणालीमध्ये नोंदवली गेली." },
                2: { title: "📍 पायरी २: अचूक ठिकाण मिळाले", desc: "GPS द्वारे अचूक ठिकाण मिळाले." },
                3: { title: "🗺️ पायरी ३: वारी क्षेत्र ओळखले", desc: "ठिकाण संबंधित वारी क्षेत्राशी जुळवले गेले." },
                4: { title: "🔴 पायरी ४: आपत्कालीन परिस्थितीची तीव्रता निश्चित केली", desc: "तीव्रता: गंभीर." },
                5: { title: "🤖 पायरी ५: AI प्रतिसादकाची शिफारस", desc: "सर्वात योग्य जवळील प्रतिसादकाची शिफारस केली." },
                6: { title: "🔔 पायरी ६: स्वयंसेवकाला सूचना पाठवली", desc: "स्वयंसेवकाला आपत्कालीन मदतीची सूचना पाठवली गेली." },
                7: { title: "🦺 पायरी ७: स्वयंसेवकाने मदत स्वीकारली", desc: "स्वयंसेवकाने केस स्वीकारली असून मदतीसाठी तयारी दर्शवली आहे." },
                8: { title: "🚶 पायरी ८: स्वयंसेवक घटनास्थळी येत आहे", desc: "स्वयंसेवक घटनास्थळी येत आहे (३२० मी • अंदाजे २ मिनिटे)." },
                9: { title: "📍 पायरी ९: स्वयंसेवक पोहोचला", desc: "स्वयंसेवक रुग्णाजवळ पोहोचला असून प्रथमोपचार सुरू केले आहेत." },
                10: { title: "🏥 पायरी १०: वैद्यकीय केंद्राने केस स्वीकारली", desc: "वैद्यकीय केंद्राने केस स्वीकारली असून १ आपत्कालीन बेड राखीव केला आहे." },
                11: { title: "🚑 पायरी ११: रुग्ण येण्याची माहिती दिली", desc: "रुग्ण पोहोचला असून उपचार सुरू झाले आहेत." },
                12: { title: "✅ पायरी १२: केस पूर्ण झाली", desc: "केस पूर्ण झाली. रुग्णावर योग्य उपचार यशस्वीरित्या झाले." }
            },

            // Exact Spoken Audio Narration Sentences in Marathi
            timeline_narrations: {
                1: "SOS पाठवले आणि नोंदणी झाली.",
                2: "GPS द्वारे अचूक ठिकाण मिळाले.",
                3: "वारी क्षेत्र ओळखले. सासवड पालखी मैदान.",
                4: "आपत्कालीन परिस्थितीची तीव्रता गंभीर निश्चित केली.",
                5: "सर्वात योग्य जवळील स्वयंसेवकाची शिफारस केली.",
                6: "स्वयंसेवकाला सूचना पाठवली आहे.",
                7: "स्वयंसेवकाने मदत स्वीकारली आहे.",
                8: "स्वयंसेवक घटनास्थळी येत आहे.",
                9: "स्वयंसेवक रुग्णाजवळ पोहोचला आहे.",
                10: "वैद्यकीय केंद्राने केस स्वीकारली आहे आणि बेड राखीव केला आहे.",
                11: "रुग्ण वैद्यकीय केंद्रात पोहोचला आहे.",
                12: "आपत्कालीन केस यशस्वीरित्या पूर्ण झाली आहे."
            },

            // Status Tags
            tag_pending: "○ प्रलंबित",
            tag_completed: "✓ पूर्ण",
            tag_waiting_vol: "⏳ स्वयंसेवकाची प्रतीक्षा",
            tag_waiting_hosp: "⏳ रुग्णालयाची प्रतीक्षा",
            tag_processing: "🔵 प्रक्रिया सुरू...",
            tag_locked: "🔒 बंद",

            // Emergency notification
            notif_title: "🚨 नवीन आपत्कालीन घटना",
            notif_msg: "झोन ०४ मध्ये गंभीर वैद्यकीय आपत्कालीन घटना नोंदवली आहे. स्वयंसेवकाची मदत आवश्यक आहे."
        },
        hi: {
            lang_code: "hi-IN",
            tagline: "आपकी सुरक्षा, एक स्पर्श में.",
            value_prop: "\\"हम सिर्फ आपातकाल दर्ज नहीं करते — पूरी राहत प्रणाली का समन्वय करते हैं.\\"",
            value_flow: "QR रिस्टबैंड → सटीक पहचान → सुरक्षित चिकित्सा प्रोफ़ाइल → AI आपातकालीन समन्वय",
            demo_desc: "डेमो डेटा • सिम्युलेटेड प्रतिक्रिया",
            reset_demo: "🔄 रीसेट डेमो",
            nav_home: "होम",
            nav_emergency: "आपातकाल",
            nav_volunteer: "स्वयंसेवक",
            nav_responder: "चिकित्सा केंद्र",
            nav_map: "सुरक्षा नक्शा",
            nav_qr_scanner: "रिस्टबैंड / QR",
            nav_command: "कंट्रोल रूम",
            wristband_id_btn: "रिस्टबैंड ID",
            palkhi_safety: "🚩 पालखी सुरक्षा समन्वय",
            hero_tagline: "\\"आपकी सुरक्षा, एक स्पर्श में.\\"",
            hero_subtext: "संत ज्ञानेश्वर एवं संत तुकाराम पालखी वारी के लिए डिजिटल स्वास्थ्य और सुरक्षा प्रणाली.",
            sos_btn_text: "🚨 आपातकालीन सहायता / SOS",
            sos_btn_sub: "सहायता के लिए दबाएं • SOS",
            current_zone: "जोन ०४ — सासवड पालखी मैदान",
            act_where_am_i: "मैं कहाँ हूँ?",
            act_medical_help: "चिकित्सा सहायता",
            act_safety_map: "सुरक्षा नक्शा",
            quick_services_title: "🛡️ त्वरित सुरक्षा सेवाएं",
            see_all: "सभी १३ सुविधाएं देखें →",
            svc_water: "पीने का पानी",
            svc_water_sub: "शुद्ध जल केंद्र",
            svc_toilets: "शौचालय",
            svc_toilets_sub: "मोबाइल शौचालय",
            svc_rest: "विश्राम",
            svc_rest_sub: "विश्राम पंडाल",
            svc_medical: "चिकित्सा केंद्र",
            svc_medical_sub: "प्राथमिक उपचार",
            svc_food: "भोजन / प्रसाद",
            svc_food_sub: "अन्नदान व भोजन",
            svc_hospitals: "अस्पताल",
            svc_hospitals_sub: "ट्रॉमा व आपातकालीन कक्ष",
            safety_id_title: "वारीसेवा सुरक्षा पहचान पत्र",
            safety_id_sub: "त्वरित सहायता के लिए अपनी जानकारी दर्ज करें.",
            label_full_name: "पूरा नाम",
            label_phone: "मोबाइल नंबर",
            btn_create_id: "सुरक्षा आईडी बनाएं",
            id_active_badge: "सुरक्षा आईडी सक्रिय है",
            btn_change_profile: "अन्य प्रोफाइल दर्ज करें",
            em_kicker: "मदद आ रही है • निश्चिंत रहें",
            em_help_requested: "आपातकालीन सहायता का अनुरोध किया गया",
            palkhi_zone: "पालखी जोन",
            nearest_landmark: "निकटतम स्थान",
            gps_precision: "जीपीएस सटीकता",
            response_timeline: "📊 आपातकालीन प्रतिक्रिया समयरेखा",
            btn_open_tactical_map: "🗺️ संपूर्ण नक्शा देखें",
            btn_report_another: "अन्य मदद दर्ज करें",
            filter_label: "फ़िल्टर:",
            map_pin_prompt: "नक्शे पर कोई पिन चुनें",
            map_pin_prompt_sub: "दूरी, मार्ग और विवरण देखने के लिए किसी भी पिन पर क्लिक करें.",
            btn_focus_pin: "🎯 नक्शे पर देखें",
            services_page_title: "वारी सुरक्षा सुविधा सूची",
            services_page_sub: "सभी १२ पालखी चरणों पर सत्यापित सुविधाएं.",
            select_zone: "जोन चुनें:",
            modal_sos_title: "आपातकालीन मदद का अनुरोध करें?",
            modal_sos_msg: "आपका सटीक स्थान दर्ज करके निकटतम वारी स्वयंसेवक को तुरंत भेजा जाएगा.",
            modal_using_id: "उपयोग की जा रही आईडी:",
            btn_cancel: "रद्द करें",
            btn_confirm_sos: "मदद भेजें (SOS)",
            acquiring_gps: "जीपीएस स्थान प्राप्त कर रहे हैं...",
            mapping_checkpoint: "निकटतम पालखी चेकपॉइंट से जोड़ रहे हैं",
            active_em_title: "आपातकालीन प्रतिक्रिया जारी है",
            view_live_response: "प्रतिक्रिया देखें →",

            // Volunteer Dashboard Strings
            vol_login_title: "स्वयंसेवक लॉगिन",
            vol_login_sub: "आधिकारिक वारी आपातकालीन सहायता पोर्टल",
            vol_demo_badge: "डेमो खाता",
            vol_demo_creds: "डेमो ID: V-001 • पासवर्ड: demo123 (रमेश कुलकर्णी • जोन ०४ • प्राथमिक उपचार प्रमाणित)",
            vol_quick_fill: "⚡ डेमो जानकारी भरें",
            vol_id_label: "स्वयंसेवक ID",
            vol_pass_label: "पासवर्ड",
            vol_login_btn: "🔐 स्वयंसेवक लॉगिन करें",
            vol_logout_btn: "🚪 लॉगआउट",
            vol_network_kicker: "वारीसेवा सत्यापित स्वयंसेवक नेटवर्क",
            vol_sector_info: "नियुक्त: जोन ०४ — सासवड पालखी मैदान • कौशल्य: प्राथमिक उपचार प्रमाणित, CPR",
            vol_status_avail: "🟢 स्थिति: उपलब्ध",
            vol_open_scanner: "📸 QR स्कैनर खोलें",
            vol_inc_dispatch: "🚨 नई आपातकालीन सहायता सूचना",
            vol_accept_btn: "🦺 केस स्वीकारें",
            vol_enroute_btn: "🚶 मदद के लिए निकलें (मार्गस्थ)",
            vol_arrived_btn: "🤝 मैं मरीज के पास पहुँचा",
            vol_scan_wb_btn: "📸 मरीज का रिस्टबैंड स्कैन करें",
            vol_escalate_btn: "🏥 अस्पताल को रेफर करें",
            vol_status_responding: "🟡 प्रतिक्रिया दे रहे हैं",
            vol_status_verified: "✓ सत्यापित",

            // Hospital Dashboard Strings
            hosp_login_title: "चिकित्सा केंद्र लॉगिन",
            hosp_login_sub: "अस्पताल एवं ट्रॉमा केंद्र समन्वय पोर्टल",
            hosp_demo_badge: "डेमो केंद्र",
            hosp_demo_creds: "केंद्र ID: H-001 • पासवर्ड: demo123 (वारीसेवा मेडिकल कैम्प — जोन ०४ • १ बेड उपलब्ध)",
            hosp_quick_fill: "⚡ डेमो जानकारी भरें",
            hosp_id_label: "केंद्र ID",
            hosp_pass_label: "पासवर्ड",
            hosp_login_btn: "🔐 चिकित्सा केंद्र लॉगिन करें",
            hosp_logout_btn: "🚪 लॉगआउट",
            hosp_network_kicker: "वारीसेवा चिकित्सा केंद्र नेटवर्क",
            hosp_bed_avail: "१ उपलब्ध",
            hosp_bed_reserved: "१ आरक्षित",
            hosp_accepting_chip: "मरीज स्वीकार कर रहे हैं",
            hosp_inc_intake: "🏥 नया मरीज आगमन",
            hosp_accept_btn: "🏥 मरीज स्वीकारें (बेड आरक्षित)",
            hosp_arrived_btn: "📍 मरीज पहुंच गया",
            hosp_treatment_btn: "🩺 उपचार शुरू हुआ",
            hosp_transfer_btn: "🚑 मरीज ट्रांसफर हुआ",
            hosp_resolve_btn: "✅ केस पूरा हुआ",
            hosp_resolved_banner: "✅ स्थिति: आपातकालीन केस सफलतापूर्वक पूरा हुआ। उपचार सफलतापूर्वक दिया गया।",

            // Command Center Strings
            cmd_title: "🛰️ कंट्रोल रूम",
            cmd_sub: "वारी आपातकालीन ऑपरेशन्स, नियंत्रण एवं सत्यापन केंद्र",
            cmd_tab_ops: "📊 ऑपरेशन्स",
            cmd_tab_vols: "🦺 स्वयंसेवक",
            cmd_tab_hosps: "🏥 चिकित्सा नेटवर्क",
            cmd_tab_dive: "🚨 लाइव घटना विश्लेषण",
            cmd_stat_registered: "कुल पंजीकृत",
            cmd_stat_verified: "सत्यापित",
            cmd_stat_available: "उपलब्ध",
            cmd_stat_responding: "प्रतिक्रिया दे रहे हैं",
            cmd_stat_pending: "सत्यापन लंबित",
            cmd_stat_accepting: "सहायता स्वीकार रहे हैं",
            cmd_stat_critical: "अत्यंत गंभीर",
            cmd_stat_high: "गंभीर",
            cmd_stat_resolved: "सुलझाई गई घटनाएं",

            // AI Recommendation
            ai_rec_title: "🤖 AI-सहायता प्राप्त रिस्पॉन्डर की सिफारिश",
            ai_why_heading: "चयन के कारण:",
            ai_reason_1: "✓ प्राथमिक उपचार प्रमाणित",
            ai_reason_2: "✓ ३५० मी दूरी (२ मिनट)",
            ai_reason_3: "✓ उसी वारी क्षेत्र में (जोन ०४)",
            ai_reason_4: "✓ मार्ग पर उपलब्ध",
            ai_kicker: "AI-सहायता प्राप्त रिस्पॉन्डर की सिफारिश",

            // Timeline Steps Translation (Exact Hindi as requested)
            timeline_steps: {
                1: { title: "🚨 चरण १: SOS भेजा गया और दर्ज किया गया", desc: "आपातकालीन घटना केंद्रीय रजिस्टर में दर्ज की गई।" },
                2: { title: "📍 चरण २: सटीक स्थान प्राप्त हुआ", desc: "GPS के माध्यम से सटीक स्थान प्राप्त हुआ।" },
                3: { title: "🗺️ चरण ३: वारी क्षेत्र की पहचान हुई", desc: "स्थान को संबंधित वारी क्षेत्र से जोड़ा गया।" },
                4: { title: "🔴 चरण ४: आपातकाल की गंभीरता निर्धारित की गई", desc: "गंभीरता: अत्यंत गंभीर।" },
                5: { title: "🤖 चरण ५: AI रिस्पॉन्डर की सिफारिश", desc: "सबसे उपयुक्त नजदीकी रिस्पॉन्डर की सिफारिश की गई।" },
                6: { title: "🔔 चरण ६: स्वयंसेवक को सूचना भेजी गई", desc: "स्वयंसेवक को आपातकालीन सहायता की सूचना भेजी गई।" },
                7: { title: "🦺 चरण ७: स्वयंसेवक ने केस स्वीकार किया", desc: "स्वयंसेवक ने केस स्वीकार कर लिया और सहायता के लिए तैयार है।" },
                8: { title: "🚶 चरण ८: स्वयंसेवक घटनास्थल की ओर जा रहा है", desc: "स्वयंसेवक घटनास्थल की ओर जा रहा है (३२० मी • लगभग २ मिनट)।" },
                9: { title: "📍 चरण ९: स्वयंसेवक पहुंच गया", desc: "स्वयंसेवक मरीज के पास पहुंच गया और प्राथमिक उपचार शुरू किया।" },
                10: { title: "🏥 चरण १०: चिकित्सा केंद्र ने केस स्वीकार किया", desc: "चिकित्सा केंद्र ने केस स्वीकार किया और १ आपातकालीन बेड आरक्षित किया।" },
                11: { title: "🚑 चरण ११: मरीज के आने की सूचना दी गई", desc: "मरीज पहुंच गया और उपचार शुरू हुआ।" },
                12: { title: "✅ चरण १२: केस पूरा हुआ", desc: "केस पूरा हुआ। मरीज को उचित चिकित्सा सहायता सफलतापूर्वक मिली।" }
            },

            // Exact Spoken Audio Narration Sentences in Hindi
            timeline_narrations: {
                1: "SOS भेजा गया और दर्ज किया गया.",
                2: "GPS के माध्यम से सटीक स्थान प्राप्त हुआ.",
                3: "वारी क्षेत्र की पहचान हुई. सासवड पालखी मैदान.",
                4: "आपातकाल की गंभीरता अत्यंत गंभीर निर्धारित की गई.",
                5: "सबसे उपयुक्त नजदीकी स्वयंसेवक की सिफारिश की गई.",
                6: "स्वयंसेवक को सूचना भेजी गई है.",
                7: "स्वयंसेवक ने केस स्वीकार किया है.",
                8: "स्वयंसेवक घटनास्थल की ओर जा रहा है.",
                9: "स्वयंसेवक मरीज के पास पहुंच गया है.",
                10: "चिकित्सा केंद्र ने केस स्वीकार किया और बेड आरक्षित किया.",
                11: "मरीज चिकित्सा केंद्र पर पहुंच गया है.",
                12: "आपातकालीन केस सफलतापूर्वक पूरा हुआ."
            },

            // Status Tags
            tag_pending: "○ लंबित",
            tag_completed: "✓ पूर्ण",
            tag_waiting_vol: "⏳ स्वयंसेवक की प्रतीक्षा",
            tag_waiting_hosp: "⏳ अस्पताल की प्रतीक्षा",
            tag_processing: "🔵 प्रक्रिया जारी...",
            tag_locked: "🔒 बंद",

            // Emergency notification
            notif_title: "🚨 नई आपातकालीन घटना",
            notif_msg: "ज़ोन ०४ में गंभीर चिकित्सा आपातकाल दर्ज की गई है। स्वयंसेवक की सहायता आवश्यक है।"
        }
    };
'''

# Find the start and end of `const i18n = {` to replace it with `multilingual_dict_js`
start_idx = js_content.find('    // Multilingual Translation Dictionaries')
if start_idx == -1:
    start_idx = js_content.find('    const i18n = {')

# Find the end of i18n object (which ends right before `// Spoken Audio Synthesis Helper` or `function getPreferredVoice`)
end_idx = js_content.find('    // Spoken Audio Synthesis Helper')

if start_idx != -1 and end_idx != -1:
    new_js = js_content[:start_idx] + multilingual_dict_js + '\n' + js_content[end_idx:]
    with open('static/script.js', 'w', encoding='utf-8') as f:
        f.write(new_js)
    print("Successfully replaced i18n dictionary in static/script.js")
else:
    print("Could not find slice indices for i18n dictionary in static/script.js", start_idx, end_idx)
