with open('static/script.js', 'r', encoding='utf-8') as f:
    js_code = f.read()

old_show_func = """    function showPhysicalWristbandModal() {
        const modal = document.getElementById('wristband-modal');
        if (!modal) return;
        modal.classList.remove('hidden');
        setWristbandViewMode('front');

        // Fetch machine's real LAN IP dynamically from the backend for physical phone scanning
        fetch('/api/network-info')
        .then(res => res.json())
        .then(data => {
            if (data.success && data.lan_ip) {
                const lanIp = data.lan_ip;
                const port = data.port || 5000;
                currentLanQrUrl = data.qr_target_url || `http://${lanIp}:${port}/public/pilgrim/WS-28471`;

                const lanIpEl = document.getElementById('wb-lan-ip-display');
                if (lanIpEl) lanIpEl.textContent = `${lanIp}:${port}`;

                const diagLanEl = document.getElementById('diag-lan-ip');
                if (diagLanEl) diagLanEl.textContent = `${lanIp}:${port}`;

                const urlTextEl = document.getElementById('wb-qr-url-text');
                if (urlTextEl) urlTextEl.textContent = currentLanQrUrl;

                const openLinkEl = document.getElementById('open-public-profile-link');
                if (openLinkEl) openLinkEl.href = currentLanQrUrl;

                // Render high-contrast 100x100px machine-readable QR code inside pure quiet box
                renderDynamicQrCode('wristband-qr-target', currentLanQrUrl, 96);
            }
        })
        .catch(() => {
            currentLanQrUrl = `${window.location.origin}/public/pilgrim/WS-28471`;
            renderDynamicQrCode('wristband-qr-target', currentLanQrUrl, 96);
        });

        showToast("✓ Physical WariSeva QR Wristband Preview Unlocked", "success");
        speakVoice("Demo access verified. Physical wristband preview unlocked.");
    }"""

new_show_func = """    function renderUnifiedMachineQr(containerId, qrUrl) {
        const container = document.getElementById(containerId);
        if (!container) return;
        container.innerHTML = '';

        // Standard machine-readable QR image generated by Python QR engine (540x540, Level H, 4-module quiet zone)
        const qrImg = document.createElement('img');
        qrImg.src = `/api/qr/image?wari_id=WS-28471&t=${Date.now()}`;
        qrImg.alt = "Machine-Scannable QR Code";
        qrImg.style.width = '276px';
        qrImg.style.height = '276px';
        qrImg.style.display = 'block';
        qrImg.style.imageRendering = 'pixelated';

        qrImg.onerror = function() {
            // Client-side QRCode.js fallback if image fetch fails
            renderDynamicQrCode(containerId, qrUrl, 276);
        };

        container.appendChild(qrImg);
    }

    function showPhysicalWristbandModal() {
        const modal = document.getElementById('wristband-modal');
        if (!modal) return;
        modal.classList.remove('hidden');
        setWristbandViewMode('front');

        // Fetch machine's real LAN IP dynamically from the backend for physical phone scanning
        fetch('/api/qr/payload?wari_id=WS-28471')
        .then(res => res.json())
        .then(data => {
            if (data.success && data.payload_url) {
                currentLanQrUrl = data.payload_url;
                const lanIp = data.lan_ip || '192.168.1.5';
                const port = data.port || 5000;

                const lanIpEl = document.getElementById('wb-lan-ip-display');
                if (lanIpEl) lanIpEl.textContent = `${lanIp}:${port}`;

                const diagLanEl = document.getElementById('diag-lan-ip');
                if (diagLanEl) diagLanEl.textContent = `${lanIp}:${port}`;

                const urlTextEl = document.getElementById('wb-qr-url-text');
                if (urlTextEl) urlTextEl.textContent = currentLanQrUrl;

                const openLinkEl = document.getElementById('open-public-profile-link');
                if (openLinkEl) openLinkEl.href = currentLanQrUrl;

                // Render high-contrast 280x280px machine-readable QR code inside unconstrained pure quiet box
                renderUnifiedMachineQr('wristband-qr-target', currentLanQrUrl);
            }
        })
        .catch(() => {
            currentLanQrUrl = `${window.location.origin}/public/pilgrim/WS-28471`;
            renderUnifiedMachineQr('wristband-qr-target', currentLanQrUrl);
        });

        showToast("✓ Physical WariSeva QR Wristband Preview Unlocked", "success");
        speakVoice("Demo access verified. Physical wristband preview unlocked.");
    }"""

assert old_show_func in js_code, "Could not find old_show_func in script.js"
js_code = js_code.replace(old_show_func, new_show_func)

with open('static/script.js', 'w', encoding='utf-8') as f:
    f.write(js_code)

print("Updated script.js to use renderUnifiedMachineQr() with full 276px pixelated high-contrast rendering!")
